entity.theme_settings.collection:
  title: 'Pagedesigner theme settings'
  route_name: entity.theme_settings.collection
  description: 'Pagedesigner Theme settings'
  parent: system.admin_config
  weight: 0

# pagedesigner_theme_settings.grid:
#   title: 'Grid settings'
#   route_name: pagedesigner_theme_settings.grid
#   description: 'Edit global grid settings'
#   parent: entity.theme_settings.collection
#   weight: 1

# pagedesigner_theme_settings.colors:
#   title: 'Color settings'
#   route_name: pagedesigner_theme_settings.colors
#   description: 'Edit global color settings'
#   parent: entity.theme_settings.collection
#   weight: 2


# pagedesigner_theme_settings.typography:
#   title: 'Typography settings'
#   route_name: pagedesigner_theme_settings.typography
#   description: 'Edit global typography settings'
#   parent: entity.theme_settings.collection
#   weight: 3

# pagedesigner_theme_settings.components:
#   title: 'Component settings'
#   route_name: pagedesigner_theme_settings.components
#   description: 'Edit component settings'
#   parent: entity.theme_settings.collection
#   weight: 4



