name: Pagedesigner Theme Settings
description: Provides an advanced interface to define global theme settings and component stying.
package: pagedesigner
type: module
core: 8.x
dependencies:
  - pagedesigner:pagedesigner

