name: Pagedesigner Theme Settings - Component styling
description: Adds component styling definitions to pagedesigner theme settings
package: pagedesigner
type: module
core: 8.x
dependencies:
  - pagedesigner:pagedesigner
  - pagedesigner_theme_settings:pagedesigner_theme_settings

